### ISSUE TITLE
[BUG] make module fails on 7.2 kernels on Fedora 44. It used to work on 7.1 kernels.

### ISSUE THREAD

**Issue by PanosPetrou** [RemixVSL/iomemory-vsl#163]
### Bug description
make module fails on 7.2 kernels on Fedora 44. It used to work on 7.1 kernels.

### How to reproduce
What are the steps to reproduce the reported issue.
```
git clone https://github.com/snuf/iomemory-vsl.git
cd iomemory-vsl
make module

Result:
........................
make[2]: Entering directory '/usr/src/kernels/7.2.5-200.fc44.x86_64'
make[3]: Entering directory '/usr/src/iomemory-vsl/root/usr/src/iomemory-vsl-3.2.16'
warning: pahole version differs from the one used to build the kernel
  The kernel was built with: 130
  You are using:             0
  CC [M]  main.o
  CC [M]  license.o
  CC [M]  mod.o
  CC [M]  pci.o
  CC [M]  sysrq.o
  CC [M]  driver_init.o
  CC [M]  kfio.o
  CC [M]  errno.o
  CC [M]  state.o
  CC [M]  kcache.o
  CC [M]  kfile.o
  CC [M]  kmem.o
  CC [M]  kfio_common.o
  CC [M]  kcpu.o
  CC [M]  kscatter.o
kfio_common.c: In function ‘kfio_strncpy’:
kfio_common.c:122:12: error: implicit declaration of function ‘strncpy’ [-Wimplicit-function-declaration]
  122 |     return strncpy(dst, src, n);
      |            ^~~~~~~
kfio_common.c:39:1: note: include ‘<string.h>’ or provide a declaration of ‘strncpy’
   38 | #include <fio/port/kfio_config.h>
  +++ |+#include <string.h>
   39 | 
kfio_common.c:122:12: error: incompatible implicit declaration of built-in function ‘strncpy’ [-Werror=builtin-declaration-mismatch]
  122 |     return strncpy(dst, src, n);
      |            ^~~~~~~
kfio_common.c:122:12: note: include ‘<string.h>’ or provide a declaration of ‘strncpy’
cc1: all warnings being treated as errors
make[5]: *** [/usr/src/kernels/7.2.5-200.fc44.x86_64/scripts/Makefile.build:289: kfio_common.o] Error 1
make[5]: *** Waiting for unfinished jobs....
kcache.c: In function ‘__kfio_create_cache’:
kcache.c:53:5: error: implicit declaration of function ‘strncpy’ [-Wimplicit-function-declaration]
   53 |     strncpy(pcache->name, name, 39);
      |     ^~~~~~~
kcache.c:35:1: note: include ‘<string.h>’ or provide a declaration of ‘strncpy’
   34 | #include <fio/port/kcache.h>
  +++ |+#include <string.h>
   35 | #include <linux/hardirq.h>  // in_atomic()
kcache.c:53:5: error: incompatible implicit declaration of built-in function ‘strncpy’ [-Werror=builtin-declaration-mismatch]
   53 |     strncpy(pcache->name, name, 39);
      |     ^~~~~~~
kcache.c:53:5: note: include ‘<string.h>’ or provide a declaration of ‘strncpy’
cc1: all warnings being treated as errors
make[5]: *** [/usr/src/kernels/7.2.5-200.fc44.x86_64/scripts/Makefile.build:289: kcache.o] Error 1
make[4]: *** [/usr/src/kernels/7.2.5-200.fc44.x86_64/Makefile:2228: .] Error 2
make[3]: *** [/usr/src/kernels/7.2.5-200.fc44.x86_64/Makefile:248: __sub-make] Error 2
make[3]: Leaving directory '/usr/src/iomemory-vsl/root/usr/src/iomemory-vsl-3.2.16'
make[2]: *** [Makefile:248: __sub-make] Error 2
make[2]: Leaving directory '/usr/src/kernels/7.2.5-200.fc44.x86_64'
make[1]: *** [Makefile:135: modules] Error 2
make[1]: Leaving directory '/usr/src/iomemory-vsl/root/usr/src/iomemory-vsl-3.2.16'
make: *** [Makefile:31: module] Error 2
root@fedora:/usr/src/iomemory-vsl#
